version: '3'
services:
  # my-app:
    # image: ${docker-registry}/my-app:1.0
    # ports:
     # - 3000:3000
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=salma                
     - MONGO_INITDB_ROOT_PASSWORD=salma123
  mongo-express:
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=salma               
     - ME_CONFIG_MONGODB_ADMINPASSWORD=salma123
     - ME_CONFIG_MONGODB_SERVER=mongodb
